module.exports = {
    // config de base
    token: 'ton token', 
    status: 'bot opensource : ',
    developerGuildID: 'ton id',
    database: 'url mongodb',

    // config ticket
    ticketName: 'ticket-',
    ticketDescription: 'ticket ouvert par',
    ticketCreate: '✅ ton ticket a été crée',
    ticketAlreadyExist: 'désoler mais tu as déja ouvert un ticket',
    ticketNoPermissions: 'désoler mais tu nas pas ler permission pour faire ça',
    ticketError: 'rééssaye plus tard',
    ticketMessageTitle: 'Bonjour, merci d avoir ouvert un ticket',
    ticketMessageDescription: 'un membre de la modération vas s occuper de ton ticket .',
    ticketClose: 'Fermer',
    ticketCloseEmoji: '📪',
    ticketLock: 'Bloquer',
    ticketLockEmoji: '🔒',
    ticketUnlock: 'Débloquer',
    ticketUnlockEmoji: '🔓',
    ticketClaim: 'Prendre',
    ticketClaimEmoji: '👋',
    ticketManage: 'Utilisateur',
    ticketManageEmoji: '➕',
    ticketManageMenuTitle: 'choisis un utilisateur.',
    ticketManageMenuEmoji: '❔',
    ticketCloseTitle: 'le ticket se ferme déjà..',
    ticketCloseDescription: 'le ticket se ferme dans 5 second',
    ticketSuccessLocked: 'le ticket est bien bloqué',
    ticketAlreadyLocked: 'le ticket est déjà bloqué',
    ticketSuccessUnlocked: 'le ticket est bien débloqué',
    ticketAlreadyUnlocked: 'ce ticket est déjà bloqué',
    ticketSuccessClaim: 'le ticket a été pris par',
    ticketAlreadyClaim: 'le ticket est déjà pris par',
    ticketDescriptionClaim: ', ticket pris par',
    ticketTranscriptMember: 'Utilisateur:',
    ticketTranscriptTicket: 'Ticket:',
    ticketTranscriptClaimed: 'Prendre:',
    ticketTranscriptModerator: 'ticket fermé par:',
    ticketTranscriptTime: 'Temps:',
    ticketMemberAdd: 'a été ajouté au ticket.',
    ticketMemberRemove: 'a été enlevé du ticket',
}